//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAFE.ServicioBackSafe {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/BackSafe.Servicio")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntUsuario", Namespace="http://schemas.datacontract.org/2004/07/BackSafe.Entidad")]
    [System.SerializableAttribute()]
    public partial class EntUsuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apmaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string appaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contraseñaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string direccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fecRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idPerfilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string telefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apmaterno {
            get {
                return this.apmaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.apmaternoField, value) != true)) {
                    this.apmaternoField = value;
                    this.RaisePropertyChanged("apmaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string appaterno {
            get {
                return this.appaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.appaternoField, value) != true)) {
                    this.appaternoField = value;
                    this.RaisePropertyChanged("appaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contraseña {
            get {
                return this.contraseñaField;
            }
            set {
                if ((object.ReferenceEquals(this.contraseñaField, value) != true)) {
                    this.contraseñaField = value;
                    this.RaisePropertyChanged("contraseña");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                if ((object.ReferenceEquals(this.direccionField, value) != true)) {
                    this.direccionField = value;
                    this.RaisePropertyChanged("direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fecRegistro {
            get {
                return this.fecRegistroField;
            }
            set {
                if ((object.ReferenceEquals(this.fecRegistroField, value) != true)) {
                    this.fecRegistroField = value;
                    this.RaisePropertyChanged("fecRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idPerfil {
            get {
                return this.idPerfilField;
            }
            set {
                if ((object.ReferenceEquals(this.idPerfilField, value) != true)) {
                    this.idPerfilField = value;
                    this.RaisePropertyChanged("idPerfil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.idUsuarioField, value) != true)) {
                    this.idUsuarioField = value;
                    this.RaisePropertyChanged("idUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rut {
            get {
                return this.rutField;
            }
            set {
                if ((object.ReferenceEquals(this.rutField, value) != true)) {
                    this.rutField = value;
                    this.RaisePropertyChanged("rut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.telefonoField, value) != true)) {
                    this.telefonoField = value;
                    this.RaisePropertyChanged("telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioBackSafe.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        SAFE.ServicioBackSafe.CompositeType GetDataUsingDataContract(SAFE.ServicioBackSafe.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<SAFE.ServicioBackSafe.CompositeType> GetDataUsingDataContractAsync(SAFE.ServicioBackSafe.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/retornarUsuarios", ReplyAction="http://tempuri.org/IService1/retornarUsuariosResponse")]
        SAFE.ServicioBackSafe.EntUsuario[] retornarUsuarios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/retornarUsuarios", ReplyAction="http://tempuri.org/IService1/retornarUsuariosResponse")]
        System.Threading.Tasks.Task<SAFE.ServicioBackSafe.EntUsuario[]> retornarUsuariosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/crearUsuario", ReplyAction="http://tempuri.org/IService1/crearUsuarioResponse")]
        bool crearUsuario(decimal rut, string contraseña, string nombre, string appaterno, string apmaterno, string direccion, decimal telefono, string email, decimal idPerfil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/crearUsuario", ReplyAction="http://tempuri.org/IService1/crearUsuarioResponse")]
        System.Threading.Tasks.Task<bool> crearUsuarioAsync(decimal rut, string contraseña, string nombre, string appaterno, string apmaterno, string direccion, decimal telefono, string email, decimal idPerfil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/modificarUsuario", ReplyAction="http://tempuri.org/IService1/modificarUsuarioResponse")]
        bool modificarUsuario(decimal rut, string contraseña, string nombre, string appaterno, string apmaterno, string direccion, decimal telefono, string email, decimal idPerfil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/modificarUsuario", ReplyAction="http://tempuri.org/IService1/modificarUsuarioResponse")]
        System.Threading.Tasks.Task<bool> modificarUsuarioAsync(decimal rut, string contraseña, string nombre, string appaterno, string apmaterno, string direccion, decimal telefono, string email, decimal idPerfil);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/crearVisitaMedica", ReplyAction="http://tempuri.org/IService1/crearVisitaMedicaResponse")]
        bool crearVisitaMedica(System.DateTime fecVisita, decimal idContrato, decimal idMedico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/crearVisitaMedica", ReplyAction="http://tempuri.org/IService1/crearVisitaMedicaResponse")]
        System.Threading.Tasks.Task<bool> crearVisitaMedicaAsync(System.DateTime fecVisita, decimal idContrato, decimal idMedico);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : SAFE.ServicioBackSafe.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<SAFE.ServicioBackSafe.IService1>, SAFE.ServicioBackSafe.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public SAFE.ServicioBackSafe.CompositeType GetDataUsingDataContract(SAFE.ServicioBackSafe.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<SAFE.ServicioBackSafe.CompositeType> GetDataUsingDataContractAsync(SAFE.ServicioBackSafe.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public SAFE.ServicioBackSafe.EntUsuario[] retornarUsuarios() {
            return base.Channel.retornarUsuarios();
        }
        
        public System.Threading.Tasks.Task<SAFE.ServicioBackSafe.EntUsuario[]> retornarUsuariosAsync() {
            return base.Channel.retornarUsuariosAsync();
        }
        
        public bool crearUsuario(decimal rut, string contraseña, string nombre, string appaterno, string apmaterno, string direccion, decimal telefono, string email, decimal idPerfil) {
            return base.Channel.crearUsuario(rut, contraseña, nombre, appaterno, apmaterno, direccion, telefono, email, idPerfil);
        }
        
        public System.Threading.Tasks.Task<bool> crearUsuarioAsync(decimal rut, string contraseña, string nombre, string appaterno, string apmaterno, string direccion, decimal telefono, string email, decimal idPerfil) {
            return base.Channel.crearUsuarioAsync(rut, contraseña, nombre, appaterno, apmaterno, direccion, telefono, email, idPerfil);
        }
        
        public bool modificarUsuario(decimal rut, string contraseña, string nombre, string appaterno, string apmaterno, string direccion, decimal telefono, string email, decimal idPerfil) {
            return base.Channel.modificarUsuario(rut, contraseña, nombre, appaterno, apmaterno, direccion, telefono, email, idPerfil);
        }
        
        public System.Threading.Tasks.Task<bool> modificarUsuarioAsync(decimal rut, string contraseña, string nombre, string appaterno, string apmaterno, string direccion, decimal telefono, string email, decimal idPerfil) {
            return base.Channel.modificarUsuarioAsync(rut, contraseña, nombre, appaterno, apmaterno, direccion, telefono, email, idPerfil);
        }
        
        public bool crearVisitaMedica(System.DateTime fecVisita, decimal idContrato, decimal idMedico) {
            return base.Channel.crearVisitaMedica(fecVisita, idContrato, idMedico);
        }
        
        public System.Threading.Tasks.Task<bool> crearVisitaMedicaAsync(System.DateTime fecVisita, decimal idContrato, decimal idMedico) {
            return base.Channel.crearVisitaMedicaAsync(fecVisita, idContrato, idMedico);
        }
    }
}
